/* *****************************************
 * CSCI205 - Software Engineering and Design
 * Fall 2015
 *
 * Name: Khoi Le & Khai Nguyen
 * Date: Oct 28, 2015
 * Time: 10:44:26 AM
 *
 * Project: csci205_hw
 * Package: hw03.view
 * File: AudioUI
 * Description:
 *
 * ****************************************
 */
package hw03.view;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JSlider;
import javax.swing.JToggleButton;

/**
 *
 * @author khainguyen
 */
public class AudioUIView extends javax.swing.JFrame {

    /**
     * Creates new form AudioUI
     *
     * @author khainguyen
     */
    public AudioUIView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel InfoPanel = new javax.swing.JPanel();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        numChannel = new javax.swing.JLabel();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        numBitsPerSample = new javax.swing.JLabel();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        numSampleRate = new javax.swing.JLabel();
        javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
        numFrameRate = new javax.swing.JLabel();
        javax.swing.JLabel jLabel15 = new javax.swing.JLabel();
        numLengthInFrame = new javax.swing.JLabel();
        javax.swing.JLabel jLabel16 = new javax.swing.JLabel();
        numLengthInByte = new javax.swing.JLabel();
        javax.swing.JPanel ProcessingPanel = new javax.swing.JPanel();
        javax.swing.JPanel AudioProcessingPanel = new javax.swing.JPanel();
        saveButton = new javax.swing.JButton();
        DFTButton = new javax.swing.JButton();
        showPeakButton = new javax.swing.JButton();
        javax.swing.JPanel volumePanel = new javax.swing.JPanel();
        javax.swing.JPanel jPanel8 = new javax.swing.JPanel();
        volumeLabel = new javax.swing.JLabel();
        volumeSlider = new javax.swing.JSlider();
        javax.swing.JLabel maxVolume = new javax.swing.JLabel();
        javax.swing.JLabel minVolume = new javax.swing.JLabel();
        volumeButton = new javax.swing.JButton();
        javax.swing.JPanel downSamplePanel = new javax.swing.JPanel();
        javax.swing.JPanel jPanel9 = new javax.swing.JPanel();
        downSampleLabel = new javax.swing.JLabel();
        downSampleSlider = new javax.swing.JSlider();
        maxDownSample = new javax.swing.JLabel();
        javax.swing.JLabel minDownSample = new javax.swing.JLabel();
        downSampleButton = new javax.swing.JButton();
        javax.swing.JPanel reverbPanel = new javax.swing.JPanel();
        javax.swing.JPanel jPanel10 = new javax.swing.JPanel();
        reverbLabel = new javax.swing.JLabel();
        reverbSlider = new javax.swing.JSlider();
        javax.swing.JLabel maxReverb = new javax.swing.JLabel();
        javax.swing.JLabel minReverb = new javax.swing.JLabel();
        reverbButton = new javax.swing.JButton();
        javax.swing.JPanel echoPanel = new javax.swing.JPanel();
        javax.swing.JPanel jPanel11 = new javax.swing.JPanel();
        delayPanel = new javax.swing.JPanel();
        delayTimeLabel = new javax.swing.JLabel();
        delayTimeSlider = new javax.swing.JSlider();
        javax.swing.JLabel maxDelayTime = new javax.swing.JLabel();
        javax.swing.JLabel minDelayTime = new javax.swing.JLabel();
        javax.swing.JPanel decayPanel = new javax.swing.JPanel();
        decayLabel = new javax.swing.JLabel();
        decaySlider = new javax.swing.JSlider();
        javax.swing.JLabel maxDecay = new javax.swing.JLabel();
        javax.swing.JLabel minDecay = new javax.swing.JLabel();
        echoButton = new javax.swing.JButton();
        waveFormPanel = new javax.swing.JPanel();
        javax.swing.JPanel jPanel5 = new javax.swing.JPanel();
        playButton = new javax.swing.JButton();
        pauseButton = new javax.swing.JButton();
        stopButton = new javax.swing.JButton();
        progressBar = new javax.swing.JSlider();
        loopToggleButton = new javax.swing.JToggleButton();
        javax.swing.JMenuBar menuBar = new javax.swing.JMenuBar();
        file = new javax.swing.JMenu();
        open = new javax.swing.JMenuItem();
        create = new javax.swing.JMenuItem();
        exit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WAVE PROCESSING");
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(1000, 900));
        setPreferredSize(new java.awt.Dimension(1000, 900));
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));

        InfoPanel.setBackground(new java.awt.Color(40, 40, 40));
        InfoPanel.setLayout(new java.awt.GridLayout(6, 2));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Open Sans Semibold", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("     CHANNEL");
        jLabel1.setFocusable(false);
        InfoPanel.add(jLabel1);

        numChannel.setBackground(new java.awt.Color(236, 240, 241));
        numChannel.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        numChannel.setForeground(new java.awt.Color(102, 255, 255));
        numChannel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numChannel.setText("2");
        InfoPanel.add(numChannel);

        jLabel2.setBackground(new java.awt.Color(236, 240, 241));
        jLabel2.setFont(new java.awt.Font("Open Sans Semibold", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("     BITS/SAMPLE");
        InfoPanel.add(jLabel2);

        numBitsPerSample.setBackground(new java.awt.Color(236, 240, 241));
        numBitsPerSample.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        numBitsPerSample.setForeground(new java.awt.Color(102, 255, 255));
        numBitsPerSample.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numBitsPerSample.setText("8");
        numBitsPerSample.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        InfoPanel.add(numBitsPerSample);

        jLabel3.setBackground(new java.awt.Color(236, 240, 241));
        jLabel3.setFont(new java.awt.Font("Open Sans Semibold", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("    SAMPLE RATE");
        InfoPanel.add(jLabel3);

        numSampleRate.setBackground(new java.awt.Color(236, 240, 241));
        numSampleRate.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        numSampleRate.setForeground(new java.awt.Color(102, 255, 255));
        numSampleRate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numSampleRate.setText("44100");
        numSampleRate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        InfoPanel.add(numSampleRate);

        jLabel5.setBackground(new java.awt.Color(236, 240, 241));
        jLabel5.setFont(new java.awt.Font("Open Sans Semibold", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("    FRAME RATE");
        InfoPanel.add(jLabel5);

        numFrameRate.setBackground(new java.awt.Color(236, 240, 241));
        numFrameRate.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        numFrameRate.setForeground(new java.awt.Color(102, 255, 255));
        numFrameRate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numFrameRate.setText("44100");
        numFrameRate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        InfoPanel.add(numFrameRate);

        jLabel15.setBackground(new java.awt.Color(236, 240, 241));
        jLabel15.setFont(new java.awt.Font("Open Sans Semibold", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("    LENGTH (FRAMES)");
        InfoPanel.add(jLabel15);

        numLengthInFrame.setBackground(new java.awt.Color(236, 240, 241));
        numLengthInFrame.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        numLengthInFrame.setForeground(new java.awt.Color(102, 255, 255));
        numLengthInFrame.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numLengthInFrame.setText("44100");
        numLengthInFrame.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        InfoPanel.add(numLengthInFrame);

        jLabel16.setBackground(new java.awt.Color(236, 240, 241));
        jLabel16.setFont(new java.awt.Font("Open Sans Semibold", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("    LENGTH (BYTES)");
        InfoPanel.add(jLabel16);

        numLengthInByte.setBackground(new java.awt.Color(236, 240, 241));
        numLengthInByte.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        numLengthInByte.setForeground(new java.awt.Color(102, 255, 255));
        numLengthInByte.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numLengthInByte.setText("44100");
        numLengthInByte.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        InfoPanel.add(numLengthInByte);

        ProcessingPanel.setBackground(new java.awt.Color(31, 31, 31));
        ProcessingPanel.setLayout(new java.awt.GridLayout(5, 1));

        AudioProcessingPanel.setBackground(new java.awt.Color(255, 255, 255));
        AudioProcessingPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 51, 51), new java.awt.Color(0, 0, 0)));
        AudioProcessingPanel.setForeground(new java.awt.Color(255, 255, 255));
        AudioProcessingPanel.setOpaque(false);
        AudioProcessingPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 12, 20));

        saveButton.setBackground(new java.awt.Color(153, 0, 51));
        saveButton.setFont(new java.awt.Font("Open Sans Semibold", 0, 15)); // NOI18N
        saveButton.setForeground(new java.awt.Color(255, 255, 255));
        saveButton.setText("SAVE");
        saveButton.setBorder(null);
        saveButton.setEnabled(false);
        saveButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        saveButton.setPreferredSize(new java.awt.Dimension(100, 35));
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        AudioProcessingPanel.add(saveButton);

        DFTButton.setBackground(new java.awt.Color(153, 0, 51));
        DFTButton.setFont(new java.awt.Font("Open Sans Semibold", 0, 15)); // NOI18N
        DFTButton.setForeground(new java.awt.Color(255, 255, 255));
        DFTButton.setText("DFT");
        DFTButton.setBorder(null);
        DFTButton.setEnabled(false);
        DFTButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        DFTButton.setPreferredSize(new java.awt.Dimension(100, 35));
        DFTButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DFTButtonActionPerformed(evt);
            }
        });
        AudioProcessingPanel.add(DFTButton);

        showPeakButton.setBackground(new java.awt.Color(153, 0, 51));
        showPeakButton.setFont(new java.awt.Font("Open Sans Semibold", 0, 15)); // NOI18N
        showPeakButton.setForeground(new java.awt.Color(255, 255, 255));
        showPeakButton.setText("DFT PEAKS");
        showPeakButton.setBorder(null);
        showPeakButton.setEnabled(false);
        showPeakButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        showPeakButton.setPreferredSize(new java.awt.Dimension(100, 35));
        showPeakButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPeakButtonActionPerformed(evt);
            }
        });
        AudioProcessingPanel.add(showPeakButton);

        ProcessingPanel.add(AudioProcessingPanel);

        volumePanel.setBackground(new java.awt.Color(36, 32, 31));
        volumePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "VOLUME", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Open Sans Semibold", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        volumePanel.setOpaque(false);

        jPanel8.setOpaque(false);
        jPanel8.setLayout(new java.awt.BorderLayout());

        volumeLabel.setFont(new java.awt.Font("Open Sans Semibold", 0, 15)); // NOI18N
        volumeLabel.setForeground(new java.awt.Color(255, 255, 255));
        volumeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        volumeLabel.setText("0");
        jPanel8.add(volumeLabel, java.awt.BorderLayout.SOUTH);

        volumeSlider.setForeground(new java.awt.Color(255, 255, 255));
        volumeSlider.setMinimum(-100);
        volumeSlider.setMinorTickSpacing(1);
        volumeSlider.setToolTipText("");
        volumeSlider.setValue(0);
        volumeSlider.setName(""); // NOI18N
        volumeSlider.setOpaque(false);
        volumeSlider.setPreferredSize(new java.awt.Dimension(250, 30));
        jPanel8.add(volumeSlider, java.awt.BorderLayout.CENTER);

        maxVolume.setFont(new java.awt.Font("Open Sans Light", 0, 14)); // NOI18N
        maxVolume.setForeground(new java.awt.Color(255, 255, 255));
        maxVolume.setText("100");
        jPanel8.add(maxVolume, java.awt.BorderLayout.LINE_END);

        minVolume.setFont(new java.awt.Font("Open Sans Light", 0, 14)); // NOI18N
        minVolume.setForeground(new java.awt.Color(255, 255, 255));
        minVolume.setText(" -100");
        jPanel8.add(minVolume, java.awt.BorderLayout.LINE_START);

        volumeButton.setBackground(new java.awt.Color(153, 0, 51));
        volumeButton.setFont(new java.awt.Font("Open Sans Semibold", 0, 15)); // NOI18N
        volumeButton.setForeground(new java.awt.Color(255, 255, 255));
        volumeButton.setText("PERFORM");
        volumeButton.setBorder(null);
        volumeButton.setEnabled(false);
        volumeButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        volumeButton.setMaximumSize(new java.awt.Dimension(600, 600));
        volumeButton.setMinimumSize(new java.awt.Dimension(60, 10));
        volumeButton.setPreferredSize(new java.awt.Dimension(100, 40));
        volumeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volumeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout volumePanelLayout = new javax.swing.GroupLayout(volumePanel);
        volumePanel.setLayout(volumePanelLayout);
        volumePanelLayout.setHorizontalGroup(
            volumePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(volumePanelLayout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(volumeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        volumePanelLayout.setVerticalGroup(
            volumePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(volumeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        ProcessingPanel.add(volumePanel);

        downSamplePanel.setBackground(new java.awt.Color(36, 32, 31));
        downSamplePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "DOWN SAMPLE", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Open Sans Semibold", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        downSamplePanel.setOpaque(false);

        jPanel9.setOpaque(false);
        jPanel9.setLayout(new java.awt.BorderLayout());

        downSampleLabel.setFont(new java.awt.Font("Open Sans Semibold", 0, 15)); // NOI18N
        downSampleLabel.setForeground(new java.awt.Color(255, 255, 255));
        downSampleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        downSampleLabel.setText("2");
        jPanel9.add(downSampleLabel, java.awt.BorderLayout.SOUTH);

        downSampleSlider.setForeground(new java.awt.Color(255, 255, 255));
        downSampleSlider.setMaximum(10);
        downSampleSlider.setMinimum(2);
        downSampleSlider.setMinorTickSpacing(1);
        downSampleSlider.setToolTipText("");
        downSampleSlider.setValue(2);
        downSampleSlider.setName(""); // NOI18N
        downSampleSlider.setOpaque(false);
        downSampleSlider.setPreferredSize(new java.awt.Dimension(250, 30));
        jPanel9.add(downSampleSlider, java.awt.BorderLayout.CENTER);

        maxDownSample.setFont(new java.awt.Font("Open Sans Light", 0, 14)); // NOI18N
        maxDownSample.setForeground(new java.awt.Color(255, 255, 255));
        maxDownSample.setText("10");
        jPanel9.add(maxDownSample, java.awt.BorderLayout.LINE_END);

        minDownSample.setFont(new java.awt.Font("Open Sans Light", 0, 14)); // NOI18N
        minDownSample.setForeground(new java.awt.Color(255, 255, 255));
        minDownSample.setText("  2    ");
        jPanel9.add(minDownSample, java.awt.BorderLayout.LINE_START);

        downSampleButton.setBackground(new java.awt.Color(153, 0, 51));
        downSampleButton.setFont(new java.awt.Font("Open Sans Semibold", 0, 15)); // NOI18N
        downSampleButton.setForeground(new java.awt.Color(255, 255, 255));
        downSampleButton.setText("PERFORM");
        downSampleButton.setBorder(null);
        downSampleButton.setEnabled(false);
        downSampleButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        downSampleButton.setMaximumSize(new java.awt.Dimension(600, 600));
        downSampleButton.setMinimumSize(new java.awt.Dimension(60, 10));
        downSampleButton.setPreferredSize(new java.awt.Dimension(100, 40));
        downSampleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downSampleButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout downSamplePanelLayout = new javax.swing.GroupLayout(downSamplePanel);
        downSamplePanel.setLayout(downSamplePanelLayout);
        downSamplePanelLayout.setHorizontalGroup(
            downSamplePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(downSamplePanelLayout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(downSampleButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        downSamplePanelLayout.setVerticalGroup(
            downSamplePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(downSampleButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        ProcessingPanel.add(downSamplePanel);

        reverbPanel.setBackground(new java.awt.Color(36, 32, 31));
        reverbPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "REVERB", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Open Sans Semibold", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        reverbPanel.setOpaque(false);

        jPanel10.setOpaque(false);
        jPanel10.setLayout(new java.awt.BorderLayout());

        reverbLabel.setFont(new java.awt.Font("Open Sans Semibold", 0, 15)); // NOI18N
        reverbLabel.setForeground(new java.awt.Color(255, 255, 255));
        reverbLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reverbLabel.setText("4");
        jPanel10.add(reverbLabel, java.awt.BorderLayout.SOUTH);

        reverbSlider.setForeground(new java.awt.Color(255, 255, 255));
        reverbSlider.setMaximum(8);
        reverbSlider.setMinimum(4);
        reverbSlider.setMinorTickSpacing(1);
        reverbSlider.setToolTipText("");
        reverbSlider.setValue(4);
        reverbSlider.setName(""); // NOI18N
        reverbSlider.setOpaque(false);
        reverbSlider.setPreferredSize(new java.awt.Dimension(250, 30));
        jPanel10.add(reverbSlider, java.awt.BorderLayout.CENTER);

        maxReverb.setFont(new java.awt.Font("Open Sans Light", 0, 14)); // NOI18N
        maxReverb.setForeground(new java.awt.Color(255, 255, 255));
        maxReverb.setText("8");
        jPanel10.add(maxReverb, java.awt.BorderLayout.LINE_END);

        minReverb.setFont(new java.awt.Font("Open Sans Light", 0, 14)); // NOI18N
        minReverb.setForeground(new java.awt.Color(255, 255, 255));
        minReverb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minReverb.setText("  4   ");
        jPanel10.add(minReverb, java.awt.BorderLayout.LINE_START);

        reverbButton.setBackground(new java.awt.Color(153, 0, 51));
        reverbButton.setFont(new java.awt.Font("Open Sans Semibold", 0, 15)); // NOI18N
        reverbButton.setForeground(new java.awt.Color(255, 255, 255));
        reverbButton.setText("PERFORM");
        reverbButton.setBorder(null);
        reverbButton.setEnabled(false);
        reverbButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        reverbButton.setMaximumSize(new java.awt.Dimension(600, 600));
        reverbButton.setMinimumSize(new java.awt.Dimension(60, 10));
        reverbButton.setPreferredSize(new java.awt.Dimension(100, 40));
        reverbButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reverbButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout reverbPanelLayout = new javax.swing.GroupLayout(reverbPanel);
        reverbPanel.setLayout(reverbPanelLayout);
        reverbPanelLayout.setHorizontalGroup(
            reverbPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reverbPanelLayout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(reverbButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        reverbPanelLayout.setVerticalGroup(
            reverbPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(reverbButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        ProcessingPanel.add(reverbPanel);

        echoPanel.setBackground(new java.awt.Color(36, 32, 31));
        echoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "ECHO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Open Sans Semibold", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        echoPanel.setOpaque(false);

        jPanel11.setOpaque(false);
        jPanel11.setLayout(new java.awt.GridLayout(1, 2));

        delayPanel.setOpaque(false);
        delayPanel.setLayout(new java.awt.BorderLayout());

        delayTimeLabel.setFont(new java.awt.Font("Open Sans Semibold", 0, 15)); // NOI18N
        delayTimeLabel.setForeground(new java.awt.Color(255, 255, 255));
        delayTimeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        delayTimeLabel.setText("0");
        delayPanel.add(delayTimeLabel, java.awt.BorderLayout.SOUTH);

        delayTimeSlider.setForeground(new java.awt.Color(255, 255, 255));
        delayTimeSlider.setMaximum(1000);
        delayTimeSlider.setMinorTickSpacing(1);
        delayTimeSlider.setToolTipText("");
        delayTimeSlider.setValue(0);
        delayTimeSlider.setName(""); // NOI18N
        delayTimeSlider.setOpaque(false);
        delayTimeSlider.setPreferredSize(new java.awt.Dimension(250, 30));
        delayPanel.add(delayTimeSlider, java.awt.BorderLayout.CENTER);

        maxDelayTime.setFont(new java.awt.Font("Open Sans Light", 0, 14)); // NOI18N
        maxDelayTime.setForeground(new java.awt.Color(255, 255, 255));
        maxDelayTime.setText("1000");
        delayPanel.add(maxDelayTime, java.awt.BorderLayout.LINE_END);

        minDelayTime.setFont(new java.awt.Font("Open Sans Light", 0, 14)); // NOI18N
        minDelayTime.setForeground(new java.awt.Color(255, 255, 255));
        minDelayTime.setText("  0   ");
        delayPanel.add(minDelayTime, java.awt.BorderLayout.LINE_START);

        jPanel11.add(delayPanel);

        decayPanel.setOpaque(false);
        decayPanel.setLayout(new java.awt.BorderLayout());

        decayLabel.setFont(new java.awt.Font("Open Sans Semibold", 0, 15)); // NOI18N
        decayLabel.setForeground(new java.awt.Color(255, 255, 255));
        decayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        decayLabel.setText("0");
        decayPanel.add(decayLabel, java.awt.BorderLayout.SOUTH);

        decaySlider.setForeground(new java.awt.Color(255, 255, 255));
        decaySlider.setMinorTickSpacing(1);
        decaySlider.setToolTipText("");
        decaySlider.setValue(0);
        decaySlider.setName(""); // NOI18N
        decaySlider.setOpaque(false);
        decaySlider.setPreferredSize(new java.awt.Dimension(250, 30));
        decayPanel.add(decaySlider, java.awt.BorderLayout.CENTER);

        maxDecay.setFont(new java.awt.Font("Open Sans Light", 0, 14)); // NOI18N
        maxDecay.setForeground(new java.awt.Color(255, 255, 255));
        maxDecay.setText("100");
        decayPanel.add(maxDecay, java.awt.BorderLayout.LINE_END);

        minDecay.setFont(new java.awt.Font("Open Sans Light", 0, 14)); // NOI18N
        minDecay.setForeground(new java.awt.Color(255, 255, 255));
        minDecay.setText("   0   ");
        decayPanel.add(minDecay, java.awt.BorderLayout.LINE_START);

        jPanel11.add(decayPanel);

        echoButton.setBackground(new java.awt.Color(153, 0, 51));
        echoButton.setFont(new java.awt.Font("Open Sans Semibold", 0, 15)); // NOI18N
        echoButton.setForeground(new java.awt.Color(255, 255, 255));
        echoButton.setText("PERFORM");
        echoButton.setBorder(null);
        echoButton.setEnabled(false);
        echoButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        echoButton.setMaximumSize(new java.awt.Dimension(600, 600));
        echoButton.setMinimumSize(new java.awt.Dimension(60, 10));
        echoButton.setPreferredSize(new java.awt.Dimension(100, 40));
        echoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                echoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout echoPanelLayout = new javax.swing.GroupLayout(echoPanel);
        echoPanel.setLayout(echoPanelLayout);
        echoPanelLayout.setHorizontalGroup(
            echoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(echoPanelLayout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(echoButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        echoPanelLayout.setVerticalGroup(
            echoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(echoButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        ProcessingPanel.add(echoPanel);

        waveFormPanel.setBackground(new java.awt.Color(0, 0, 0));
        waveFormPanel.setMinimumSize(new java.awt.Dimension(207, 404));
        waveFormPanel.setLayout(new java.awt.GridLayout(1, 0));

        jPanel5.setBackground(new java.awt.Color(0, 51, 51));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 10));

        playButton.setBackground(new java.awt.Color(153, 0, 51));
        playButton.setFont(new java.awt.Font("Open Sans Semibold", 0, 15)); // NOI18N
        playButton.setForeground(new java.awt.Color(255, 255, 255));
        playButton.setText("PLAY");
        playButton.setBorder(null);
        playButton.setEnabled(false);
        playButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        playButton.setPreferredSize(new java.awt.Dimension(100, 40));
        playButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playButtonActionPerformed(evt);
            }
        });
        jPanel5.add(playButton);

        pauseButton.setBackground(new java.awt.Color(153, 0, 51));
        pauseButton.setFont(new java.awt.Font("Open Sans Semibold", 0, 15)); // NOI18N
        pauseButton.setForeground(new java.awt.Color(255, 255, 255));
        pauseButton.setText("PAUSE");
        pauseButton.setBorder(null);
        pauseButton.setEnabled(false);
        pauseButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pauseButton.setPreferredSize(new java.awt.Dimension(100, 40));
        pauseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseButtonActionPerformed(evt);
            }
        });
        jPanel5.add(pauseButton);

        stopButton.setBackground(new java.awt.Color(153, 0, 51));
        stopButton.setFont(new java.awt.Font("Open Sans Semibold", 0, 15)); // NOI18N
        stopButton.setForeground(new java.awt.Color(255, 255, 255));
        stopButton.setText("STOP");
        stopButton.setBorder(null);
        stopButton.setEnabled(false);
        stopButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        stopButton.setPreferredSize(new java.awt.Dimension(100, 40));
        stopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopButtonActionPerformed(evt);
            }
        });
        jPanel5.add(stopButton);

        progressBar.setForeground(new java.awt.Color(255, 255, 255));
        progressBar.setMinorTickSpacing(1);
        progressBar.setToolTipText("");
        progressBar.setValue(0);
        progressBar.setName(""); // NOI18N
        progressBar.setOpaque(false);
        progressBar.setPreferredSize(new java.awt.Dimension(450, 30));
        jPanel5.add(progressBar);

        loopToggleButton.setBackground(new java.awt.Color(153, 0, 51));
        loopToggleButton.setFont(new java.awt.Font("Open Sans Semibold", 0, 14)); // NOI18N
        loopToggleButton.setForeground(new java.awt.Color(255, 255, 255));
        loopToggleButton.setText("LOOP");
        loopToggleButton.setBorder(null);
        loopToggleButton.setEnabled(false);
        loopToggleButton.setMinimumSize(new java.awt.Dimension(60, 40));
        loopToggleButton.setPreferredSize(new java.awt.Dimension(60, 40));
        jPanel5.add(loopToggleButton);

        menuBar.setBackground(new java.awt.Color(0, 51, 51));
        menuBar.setBorder(null);
        menuBar.setPreferredSize(new java.awt.Dimension(80, 30));

        file.setBackground(new java.awt.Color(0, 51, 51));
        file.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        file.setForeground(new java.awt.Color(255, 255, 255));
        file.setText("FILE");
        file.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        file.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        file.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        file.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        file.setPreferredSize(new java.awt.Dimension(75, 25));

        open.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        open.setBackground(new java.awt.Color(0, 51, 51));
        open.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        open.setForeground(new java.awt.Color(255, 255, 255));
        open.setText("Open FIle");
        open.setBorder(null);
        open.setPreferredSize(new java.awt.Dimension(120, 30));
        file.add(open);

        create.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        create.setBackground(new java.awt.Color(0, 51, 51));
        create.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        create.setForeground(new java.awt.Color(255, 255, 255));
        create.setText("Create");
        create.setBorder(null);
        create.setPreferredSize(new java.awt.Dimension(120, 30));
        file.add(create);

        exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        exit.setBackground(new java.awt.Color(0, 51, 51));
        exit.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setText("Exit");
        exit.setBorder(null);
        exit.setPreferredSize(new java.awt.Dimension(120, 30));
        file.add(exit);

        menuBar.add(file);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(InfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(ProcessingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(waveFormPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(waveFormPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ProcessingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DFTButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DFTButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DFTButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveButtonActionPerformed

    private void showPeakButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPeakButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showPeakButtonActionPerformed

    private void volumeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volumeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_volumeButtonActionPerformed

    private void downSampleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downSampleButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_downSampleButtonActionPerformed

    private void reverbButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reverbButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reverbButtonActionPerformed

    private void echoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_echoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_echoButtonActionPerformed

    private void playButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_playButtonActionPerformed

    private void stopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stopButtonActionPerformed

    private void pauseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pauseButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DFTButton;
    private javax.swing.JMenuItem create;
    private javax.swing.JLabel decayLabel;
    private javax.swing.JSlider decaySlider;
    private javax.swing.JPanel delayPanel;
    private javax.swing.JLabel delayTimeLabel;
    private javax.swing.JSlider delayTimeSlider;
    private javax.swing.JButton downSampleButton;
    private javax.swing.JLabel downSampleLabel;
    private javax.swing.JSlider downSampleSlider;
    private javax.swing.JButton echoButton;
    private javax.swing.JMenuItem exit;
    private javax.swing.JMenu file;
    private javax.swing.JToggleButton loopToggleButton;
    private javax.swing.JLabel maxDownSample;
    private javax.swing.JLabel numBitsPerSample;
    private javax.swing.JLabel numChannel;
    private javax.swing.JLabel numFrameRate;
    private javax.swing.JLabel numLengthInByte;
    private javax.swing.JLabel numLengthInFrame;
    private javax.swing.JLabel numSampleRate;
    private javax.swing.JMenuItem open;
    private javax.swing.JButton pauseButton;
    private javax.swing.JButton playButton;
    private javax.swing.JSlider progressBar;
    private javax.swing.JButton reverbButton;
    private javax.swing.JLabel reverbLabel;
    private javax.swing.JSlider reverbSlider;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton showPeakButton;
    private javax.swing.JButton stopButton;
    private javax.swing.JButton volumeButton;
    private javax.swing.JLabel volumeLabel;
    private javax.swing.JSlider volumeSlider;
    private javax.swing.JPanel waveFormPanel;
    // End of variables declaration//GEN-END:variables

    public JButton getDFTButton() {
        return DFTButton;
    }

    public JMenuItem getCreate() {
        return create;
    }

    public JButton getShowPeakButton() {
        return showPeakButton;
    }

    public JLabel getDecayLabel() {
        return decayLabel;
    }

    public JSlider getDecaySlider() {
        return decaySlider;
    }

    public JPanel getDelayPanel() {
        return delayPanel;
    }

    public JLabel getDelayTimeLabel() {
        return delayTimeLabel;
    }

    public JSlider getDelayTimeSlider() {
        return delayTimeSlider;
    }

    public JButton getDownSampleButton() {
        return downSampleButton;
    }

    public JLabel getDownSampleLabel() {
        return downSampleLabel;
    }

    public JSlider getDownSampleSlider() {
        return downSampleSlider;
    }

    public JMenuItem getExit() {
        return exit;
    }

    public JMenu getFile() {
        return file;
    }

    public JLabel getMaxDownSample() {
        return maxDownSample;
    }

    public JLabel getNumBitsPerSample() {
        return numBitsPerSample;
    }

    public JLabel getNumChannel() {
        return numChannel;
    }

    public JLabel getNumFrameRate() {
        return numFrameRate;
    }

    public JLabel getNumLengthInByte() {
        return numLengthInByte;
    }

    public JLabel getNumLengthInFrame() {
        return numLengthInFrame;
    }

    public JLabel getNumSampleRate() {
        return numSampleRate;
    }

    public JMenuItem getOpen() {
        return open;
    }

    public JLabel getReverbLabel() {
        return reverbLabel;
    }

    public JSlider getReverbSlider() {
        return reverbSlider;
    }

    public JButton getSaveButton() {
        return saveButton;
    }

    public JButton getVolumeButton() {
        return volumeButton;
    }

    public JLabel getVolumeLabel() {
        return volumeLabel;
    }

    public JButton getReverbButton() {
        return reverbButton;
    }

    public JButton getEchoButton() {
        return echoButton;
    }

    public JSlider getVolumeSlider() {
        return volumeSlider;
    }

    public JButton getPlayButton() {
        return playButton;
    }

    public JButton getStopButton() {
        return stopButton;
    }

    public JSlider getProgressBar() {
        return progressBar;
    }

    public JToggleButton getLoopToggleButton() {
        return loopToggleButton;
    }

    public JPanel getWaveFormPanel() {
        return waveFormPanel;
    }

    public JButton getPauseButton() {
        return pauseButton;
    }

}
